# Generated by Django 4.2 on 2024-09-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=100)),
                ('leave_date', models.DateField()),
                ('leave_reason', models.TextField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_password', models.CharField(max_length=100)),
                ('email_body', models.TextField()),
                ('email_subject', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
