# Generated by Django 4.2 on 2024-09-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequestsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
