# Generated by Django 4.2 on 2024-09-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequestsapi', '0002_alter_leaverequest_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
