# Generated by Django 4.2 on 2024-09-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequestsapi', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='LeaveRequests',
        ),
        migrations.RemoveField(
            model_name='leavetracking',
            name='emp',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='LeaveTracking',
        ),
    ]
