# Generated by Django 4.2 on 2024-09-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('StartShiftTimings', models.CharField(blank=True, max_length=50, null=True)),
                ('EndShiftTimings', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_image', models.ImageField(blank=True, null=True, upload_to='emp_image/')),
            ],
        ),
        migrations.CreateModel(
            name='leave_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('annual_total', models.IntegerField()),
                ('annual_consumed', models.IntegerField()),
                ('annual_remaining', models.IntegerField()),
                ('sick_total', models.IntegerField()),
                ('sick_consumed', models.IntegerField()),
                ('sick_remaining', models.IntegerField()),
                ('casual_total', models.IntegerField()),
                ('casual_consumed', models.IntegerField()),
                ('casual_remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='leave_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('leave_duration', models.IntegerField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.employees')),
            ],
            options={
                'unique_together': {('emp_id', 'leave_date')},
            },
        ),
    ]
