# Generated by Django 4.2 on 2024-09-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='HOD_HR',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
